### ISSUE TITLE
Release to NPM

### ISSUE THREAD

**Issue by axe312ger** [loewexy/gpsd-fake#1]
Hey Lucas,

I just gave it a try, since I am planning to use gpsd via JS on my Raspberry. Since my development machine does not have a GPS device, I was looking for options.

Your code runs great, my test parser is working fine on the Raspberry and with your fake gpsd server, also.

Are you willing to release it to npm? I'd love to use it as development dependency for my local dev environment.

Let me know what you think, I can help with creating a lib out of it and push it to npm.

Greetings from Berlin,
Benedikt

**Comment by loewexy** [comment]
I would be okay with publishing it to npm, but I don't know what is required to do so.

Also I am not shure if creating a libary is a good idea, because the software should be run as a seperate process so that there is the same relation for the software when using gpsd-fake as there would be if gpsd is used.

**Comment by axe312ger** [comment]
Hey there,

you can also release software to NPM. It does not have to be a "normal" dependency or library.

We can also structure it to register as global process, so you can use it just as a normal command, totally separated from other code.

So you just install via:
`npm install --global gpsd-fake`

And run the tool on your CLI from any folder via:
`gpsd-fake`

(There is still the option to download it as local dependency for one project and make the "binary" only available within the project directory)

If you are willing to merge it, I can do a Pull-Request with everything ready for release? :)

The actual publishing to npm is done within one minute, all you have to do is:
* Make sure to use semver for proper versioning: https://docs.npmjs.com/getting-started/semantic-versioning
* Publish it to npm: https://docs.npmjs.com/getting-started/publishing-npm-packages
(Some minimal config preperation needed but I can do this in the PR)


Benedikt

**Comment by loewexy** [comment]
Ok that sounds reasonable. If you do the adjustments in a pull request I will publish it to npm.

**Comment by axe312ger** [comment]
Kewl, I might not be able to do it straight away but I hope within the next 2 weeks. Thank you <3

**Comment by axe312ger** [comment]
Awesome!!! Now just release it:

`npm version minor` (or major, your decision)
`npm publish`

:)

**Comment by loewexy** [comment]
I just stay with 1.0.0 for the first Release to NPM until now the version was only a placeholder.

It should be available now :) thanks for your help

**Comment by axe312ger** [comment]
Great, works like charm. <3
